### ISSUE TITLE
Direct link to specific level - possible?

### ISSUE THREAD

**Issue by dajare** [ggorlen/sokoban#2]
Hi! I'm really enjoying playing your implementation of [sokoban](https://ggorlen.github.io/sokoban/). Thanks for it!

As I work my way through the levels, of course I'm press-holding `.`, or `,` if I go "too far". Is it possible to construct a link to go directly to a specific level? I took at look at the page's source code, but couldn't spot anything obvious.

Obviously, this isn't a bug! :) Just wondering. Thanks for any help with this!

David

**Comment by ggorlen** [comment]
Great suggestion! Feel free to submit a PR if you'd like to add the feature. If not, I'll add it when time permits.

Quick specification (let me know if this differs from what you imagined):
- The site should always render the current level in the query, like https://ggorlen.github.io/sokoban?level=42
- Changing a level changes the `level=` value
- When the page is loaded, the query string is read:
  - If `level=` isn't present or is out of bounds or an illegal value, set it to `level=1`
  - Otherwise, `level=` is not empty and points to a valid level number, switch to that level.

~~Somewhat related functionality would be to store the current level in local storage (not shareable/bookmarkable, but might similarly help get back to where you were).~~ (I guess this is already implemented with `v` and `b`)

**Comment by dajare** [comment]
Thanks for being open to this suggestion, even enthusiastically so. :)

Unfortunately, I'm no coder so implementing this is waaaay beyond my hobbyist (dabbling with PHP) pseudo-skills. Your first suggestion, `https://ggorlen.github.io/sokoban?level=42` type thing, is exactly what I had in mind.

If you're able to get around to it, I guess it could be documented under "Controls"? 

Thanks again!

**Comment by ggorlen** [comment]
Closed by https://github.com/ggorlen/sokoban/pull/3. Please let me know if you find any bugs or weird behavior, or doesn't work well for your needs.

**Comment by dajare** [comment]
> Closed by #3. Please let me know if you find any bugs or weird behavior, or doesn't work well for your needs.

A thing of beauty! :) Works perfectly. Thanks again!
